[workspace]
members = [
    "crates/dream_core",
    "crates/dream_forge",
    "crates/seed_architect",
    "crates/lucid_runtime",
    "crates/dream_offline"
]
resolver = "2"

[workspace.dependencies]
# ğŸ§  CORE & MATHS
# "simd" est retirÃ© car glam 0.24 l'active automatiquement via nos flags AVX2
glam = { version = "0.24", features = ["fast-math", "bytemuck"] } 
bytemuck = { version = "1.14", features = ["derive", "extern_crate_alloc"] }
bitflags = "2.4"

# ğŸŒ‹ VULKAN & MEMORY (SAO INFRA)
ash = "0.37"
ash-window = "0.12"
gpu-allocator = "0.25"
raw-window-handle = "0.5"

# âš™ï¸ SYSTEM & ASYNC
winit = "0.28"
tokio = { version = "1.32", features = ["full"] }
log = "0.4"
env_logger = "0.10"

# ğŸ§¬ ASSETS & SERIALIZATION
rkyv = { version = "0.7", features = ["validation"] }
zstd = "0.13"
russimp = "1.0"
meshopt = "0.1"